spring:
  application:
    name: helpguru-backend
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:aws-0-ap-southeast-1.pooler.supabase.com}:${DB_PORT:5432}/${DB_NAME:postgres}?sslmode=require
    username: ${DB_USER:postgres.wrjwhiyomhlqlcuvxsgf}
    password: ${DB_PASS:MuSfi0191Mu}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate # Database driven strictly by SQL DDL migration
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

# Security JWT configuration
helpguru:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000 # 24 hours
    refresh-expiration-ms: 604800000 # 7 days

# Monitoring Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
